---
extends:
  - airbnb
  - prettier
  - prettier/react
rules:
  react/require-default-props: off
  react/jsx-filename-extension:
    - error
    - extensions:
      - .js
  jsx-a11y/anchor-is-valid:
    - error
    - components:
        - Link
      specialLink:
        - to
parser: 'babel-eslint'
env:
  browser: true
globals:
  graphql: false