[build]
  publish = "public"
  command = "npm run build"
[build.environment]
  YARN_VERSION = "1.9.4"
  YARN_FLAGS = "--no-ignore-optional"

[[redirects]]
  from = "/eod_1.0.0.pdf"
  to = "https://eod.oms.no/swagger-ui"
